; This relies on the defintions of BPv7 "bpv7.cddl"

; The block-type-specific data for BIB and BCB
ext-data-asb = [
  targets: [1* target-block-num],
  context-id: int,
  flags: uint .bits asb-flag-bits, ; if the sec-params-present is set
  ? security-source: eid, ; if the sec-source-present is set
  ? parameters: param-list,
  target-results: [1* result-list]
]
target-block-num = uint
asb-flag-bits = &(
  sec-params-present: 1,
  sec-source-present: 2
)

; Alternatives can be added to the sockets for each context ID
param-list = [1* $bpsec-param-pair .within asb-id-value-structure]
result-list = [1* $bpsec-result-pair .within asb-id-value-structure]

; Interpretation of the pair depends on the context-id and whether
; it is a parameter or a result.
asb-id-value-structure = [
  id: uint,
  value: any
]

$extension-block-structure /= extension-block-use<98, embedded-cbor<ext-data-asb>>
$extension-block-structure /= extension-block-use<99, embedded-cbor<ext-data-asb>>
